name: Deploy to Ubuntu Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          # 1. 경로 이동 (오타 주의! recuit_filter)
          cd /home/ubuntu/recuit_filter

          # 2. 최신 코드 받기
          git pull https://github.com/dlwlsgh1118-cpu/recuit_filter.git main

          # 3. 가상환경 켜기 & 패키지 설치
          source venv/bin/activate
          pip install -r requirements.txt

          # 4. 기존 서버 죽이기
          pkill -f streamlit || true
          

          # 5. 서버 켜고 연결 끊기 (nohup ... & 만으로는 부족할 때가 있음)
          # 입력/출력을 완전히 끊어서 깃허브가 기다리지 않게 함
          # --server.headless true : 화면 없는 서버 모드로 켜라
          # --browser.gatherUsageStats false : 이메일 묻지 말고 통계 수집도 하지 마라
          nohup streamlit run app.py > output.log 2>&1 &
          
          # 6. 서버가 켜질 시간 잠시 대기
          sleep 3
          
          # 7. 명시적으로 종료 성공 알림
          echo "Deployment successful!"